# Cleanup redirects config file.
name: Redirects cleanup PR

on:
  schedule:
    - cron: '0 7 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'
          cache: 'yarn'
      - run: yarn
      - run: yarn run clean-redirects
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Redirects config cleanup ${{ env.current_date }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: clean_redirects_action_${{ env.current_date }}
          delete-branch: true
          title: 'Redirects config cleanup ${{ env.current_date }}'